### PR TITLE
Updated the Dataset links

### PR DESCRIPTION
**Pull request by rushirajsherlocked**

### CODE REVIEW

**Comment by JingyunLiang** [comment]
Why update these two dataset links?

**Comment by rushirajsherlocked** [comment]
Actually I can't open the reference links for OST and WED dataset. The webpage doesn't load for OST dataset - [old link](https://openmmlab.oss-cn-hangzhou.aliyuncs.com/datasets/OST_dataset.zip) whereas the WED dataset web page doesn't even open for some reasons, so just updated them to these new links

(1) [OST Dataset](https://drive.google.com/drive/folders/1iZfzAxAwOpeutz27HC56_y5RNqnsPPKr)
(2) [WED Dataset](http://ivc.uwaterloo.ca/database/WaterlooExploration/)

**Comment by JingyunLiang** [comment]
Thanks for your udpate. For OST, it's from `aliyuncs.com` and it works for me. I will add your link in case that someone cannot access it. For WED, I have solved the bug by adding `https://` at the start of the link. It should work now.

**Comment by rushirajsherlocked** [comment]
Thanks!

**Comment by JingyunLiang** [comment]
I have added the link. Thanks for your pull request.

**Pull request closed without merging**
