### PR TITLE
Add Docker environment & web demo

### PR DESCRIPTION
**Pull request by CJWBW**
Hey @JingyunLiang ! 👋 

Thank you for merging the PR from HCFlow yesterday! We found this model of yours very cool as well so we made a demo too.

This pull request makes it possible to run your model inside a Docker environment, which makes it easier for other people to run it.  We're using an open source tool called [Cog](https://github.com/replicate/cog) to make this process easier.

This also means we can make a web page where other people can try out your model! View it here: https://replicate.ai/jingyunliang/swinir

[Claim your page here](https://replicate.ai/login/github/?next=/jingyunliang/swinir?published=1) so you can edit it, and we'll feature it on our website and tweet about it too. It would give you the ownership of the page and we recommend you doing so :)

In case you're wondering who I am, I'm from [Replicate](https://replicate.ai/home), where we're trying to make machine learning reproducible. We got frustrated that we couldn't run all the really interesting ML work being done. So, we're going round implementing models we like. 😊

### CODE REVIEW

**Review by JingyunLiang — APPROVED** [review]
Add Docker environment & web demo, thanks to @CJWBW

**Comment by JingyunLiang** [comment]
@CJWBW I suggest that you can design something like [ <a href="https://colab.research.google.com/gist/JingyunLiang/a5e3e54bc9ef8d7bf594f6fee8208533/swinir-demo-on-real-world-image-sr.ipynb">google colab logo</a>](https://colab.research.google.com/gist/JingyunLiang/a5e3e54bc9ef8d7bf594f6fee8208533/swinir-demo-on-real-world-image-sr.ipynb) .  A distinguished icon is more eye-catching and gives people better impression.

**Comment by CJWBW** [comment]
> @CJWBW I suggest that you can design something like [ ](https://colab.research.google.com/gist/JingyunLiang/a5e3e54bc9ef8d7bf594f6fee8208533/swinir-demo-on-real-world-image-sr.ipynb)[google colab logo](https://colab.research.google.com/gist/JingyunLiang/a5e3e54bc9ef8d7bf594f6fee8208533/swinir-demo-on-real-world-image-sr.ipynb) . A distinguished icon is more eye-catching and gives people better impression.

Thank you very much, that is a great suggestion! We are working on it :)

**Comment by zeke** [comment]
Wow this model is pretty impressive. Just like in the movies when they say "enhance!" but it actually works!

@JingyunLiang have you had a chance to check out the demo page @CJWBW created for you? You can [claim your page here](https://replicate.ai/login/github/?next=/jingyunliang/swinir?published=1) so you can edit it, and we'll feature it on our website and tweet about it too.

---

Screen Shot 2021-09-21 at 10 25 02 AM

**Pull request merged**
